
OCT_CLASSES = [
    "background","RNFL","GCL","IPL","INL","OPL","ONL","ISOS","RPE","CHOROID","nerves-vessels-OPTICDISC"
]
OCT_NUM_CLASSES = len(OCT_CLASSES)


OCT_IMAGE_SIZE = 384
OCT_INPUT_SHAPE = (OCT_IMAGE_SIZE, OCT_IMAGE_SIZE, 3)


DEFAULT_ALPHA = 0.35